version: '3.9'

services:
  client:
    image: node:14.19.1
    command: sh -c "npm i && npm run lint:fix && npm run format && npm start"
    ports:
      - "3000:3000"
    working_dir: /client
    volumes:
      - ./:/client
