version: "3.9"

services:
  application:
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - ./:/user
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:userservice@postgres:5432/user
    depends_on:
      - db
  
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=user 
      - POSTGRES_PASSWORD=userservice