FROM python:3.9.13
WORKDIR /user 
COPY ./requirements.txt /user/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /user/requirements.txt
COPY . /user
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]